va = float(input("Ingrese la velocidad del primer auto: "))
vb = float(input("Ingrese la velocidad del segundo auto: "))
d = float(input("Ingrese la distancia entre ellos: "))
t = d/(va+vb)
print("los cuerpos se van a encontrar en ",t,"segundos")